name: Execute Test Manualy
on:
  workflow_dispatch:
jobs:        
  ExecuteTests:
    name: 'Executing automated test cases'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.45.0-jammy
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '22'
    - name: Build and install
      run: mvn -B install -DskipTests --no-transfer-progress 
    - name: Run tests
      run: mvn test -PGrid

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Cucumber Reports
        path: target/Reports
